// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/git.dart';
import 'api/models.dart';
import 'api/simple.dart';
import 'api/update.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<OperationEvent> dco_decode_StreamSink_operation_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<RepositoryWatchEvent>
  dco_decode_StreamSink_repository_watch_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CloneOptions dco_decode_box_autoadd_clone_options(dynamic raw);

  @protected
  CommitOptions dco_decode_box_autoadd_commit_options(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FileChange dco_decode_box_autoadd_file_change(dynamic raw);

  @protected
  OperationResult dco_decode_box_autoadd_operation_result(dynamic raw);

  @protected
  RebasePlan dco_decode_box_autoadd_rebase_plan(dynamic raw);

  @protected
  RepositoryInitOptions dco_decode_box_autoadd_repository_init_options(
    dynamic raw,
  );

  @protected
  SubmoduleAddOptions dco_decode_box_autoadd_submodule_add_options(dynamic raw);

  @protected
  SubtreeInfo dco_decode_box_autoadd_subtree_info(dynamic raw);

  @protected
  SubtreeOperationOptions dco_decode_box_autoadd_subtree_operation_options(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BranchInfo dco_decode_branch_info(dynamic raw);

  @protected
  BranchPage dco_decode_branch_page(dynamic raw);

  @protected
  ChangeKind dco_decode_change_kind(dynamic raw);

  @protected
  CherryPickApplicability dco_decode_cherry_pick_applicability(dynamic raw);

  @protected
  CloneOptions dco_decode_clone_options(dynamic raw);

  @protected
  CloneResult dco_decode_clone_result(dynamic raw);

  @protected
  CommitCursorPage dco_decode_commit_cursor_page(dynamic raw);

  @protected
  CommitDefaults dco_decode_commit_defaults(dynamic raw);

  @protected
  CommitDetail dco_decode_commit_detail(dynamic raw);

  @protected
  CommitOptions dco_decode_commit_options(dynamic raw);

  @protected
  CommitPage dco_decode_commit_page(dynamic raw);

  @protected
  CommitReference dco_decode_commit_reference(dynamic raw);

  @protected
  CommitReferenceKind dco_decode_commit_reference_kind(dynamic raw);

  @protected
  CommitSigningMode dco_decode_commit_signing_mode(dynamic raw);

  @protected
  CommitSummary dco_decode_commit_summary(dynamic raw);

  @protected
  ConflictFile dco_decode_conflict_file(dynamic raw);

  @protected
  ConflictRegion dco_decode_conflict_region(dynamic raw);

  @protected
  DiffDocument dco_decode_diff_document(dynamic raw);

  @protected
  DiffFile dco_decode_diff_file(dynamic raw);

  @protected
  DiffHunk dco_decode_diff_hunk(dynamic raw);

  @protected
  DiffLine dco_decode_diff_line(dynamic raw);

  @protected
  DiffLineKind dco_decode_diff_line_kind(dynamic raw);

  @protected
  ExternalEditor dco_decode_external_editor(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileChange dco_decode_file_change(dynamic raw);

  @protected
  FileChangePage dco_decode_file_change_page(dynamic raw);

  @protected
  GitCapabilities dco_decode_git_capabilities(dynamic raw);

  @protected
  GitConfigEntry dco_decode_git_config_entry(dynamic raw);

  @protected
  GitConfigScope dco_decode_git_config_scope(dynamic raw);

  @protected
  GitConfigSnapshot dco_decode_git_config_snapshot(dynamic raw);

  @protected
  GitignoreTemplate dco_decode_gitignore_template(dynamic raw);

  @protected
  GraphLane dco_decode_graph_lane(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BranchInfo> dco_decode_list_branch_info(dynamic raw);

  @protected
  List<CommitReference> dco_decode_list_commit_reference(dynamic raw);

  @protected
  List<CommitSummary> dco_decode_list_commit_summary(dynamic raw);

  @protected
  List<ConflictRegion> dco_decode_list_conflict_region(dynamic raw);

  @protected
  List<DiffFile> dco_decode_list_diff_file(dynamic raw);

  @protected
  List<DiffHunk> dco_decode_list_diff_hunk(dynamic raw);

  @protected
  List<DiffLine> dco_decode_list_diff_line(dynamic raw);

  @protected
  List<FileChange> dco_decode_list_file_change(dynamic raw);

  @protected
  List<GitConfigEntry> dco_decode_list_git_config_entry(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RebasePlanItem> dco_decode_list_rebase_plan_item(dynamic raw);

  @protected
  List<RemoteDetails> dco_decode_list_remote_details(dynamic raw);

  @protected
  List<RemoteInfo> dco_decode_list_remote_info(dynamic raw);

  @protected
  List<ResetCommit> dco_decode_list_reset_commit(dynamic raw);

  @protected
  List<StashEntry> dco_decode_list_stash_entry(dynamic raw);

  @protected
  List<SubmoduleInfo> dco_decode_list_submodule_info(dynamic raw);

  @protected
  List<SubtreeInfo> dco_decode_list_subtree_info(dynamic raw);

  @protected
  MergeControl dco_decode_merge_control(dynamic raw);

  @protected
  OperationEvent dco_decode_operation_event(dynamic raw);

  @protected
  OperationPhase dco_decode_operation_phase(dynamic raw);

  @protected
  OperationResult dco_decode_operation_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  FileChange? dco_decode_opt_box_autoadd_file_change(dynamic raw);

  @protected
  OperationResult? dco_decode_opt_box_autoadd_operation_result(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PullMode dco_decode_pull_mode(dynamic raw);

  @protected
  RebaseAction dco_decode_rebase_action(dynamic raw);

  @protected
  RebaseControl dco_decode_rebase_control(dynamic raw);

  @protected
  RebasePlan dco_decode_rebase_plan(dynamic raw);

  @protected
  RebasePlanItem dco_decode_rebase_plan_item(dynamic raw);

  @protected
  RemoteDetails dco_decode_remote_details(dynamic raw);

  @protected
  RemoteInfo dco_decode_remote_info(dynamic raw);

  @protected
  RepositoryInitOptions dco_decode_repository_init_options(dynamic raw);

  @protected
  RepositoryInitResult dco_decode_repository_init_result(dynamic raw);

  @protected
  RepositorySnapshot dco_decode_repository_snapshot(dynamic raw);

  @protected
  RepositorySnapshotPage dco_decode_repository_snapshot_page(dynamic raw);

  @protected
  RepositoryState dco_decode_repository_state(dynamic raw);

  @protected
  RepositoryWatchEvent dco_decode_repository_watch_event(dynamic raw);

  @protected
  ResetCommit dco_decode_reset_commit(dynamic raw);

  @protected
  ResetMode dco_decode_reset_mode(dynamic raw);

  @protected
  ResetPreview dco_decode_reset_preview(dynamic raw);

  @protected
  SequenceControl dco_decode_sequence_control(dynamic raw);

  @protected
  SparseCheckoutState dco_decode_sparse_checkout_state(dynamic raw);

  @protected
  StashEntry dco_decode_stash_entry(dynamic raw);

  @protected
  SubmoduleAddOptions dco_decode_submodule_add_options(dynamic raw);

  @protected
  SubmoduleInfo dco_decode_submodule_info(dynamic raw);

  @protected
  SubmodulePage dco_decode_submodule_page(dynamic raw);

  @protected
  SubmoduleRemovePreview dco_decode_submodule_remove_preview(dynamic raw);

  @protected
  SubmoduleState dco_decode_submodule_state(dynamic raw);

  @protected
  SubmoduleUpdateMode dco_decode_submodule_update_mode(dynamic raw);

  @protected
  SubtreeAction dco_decode_subtree_action(dynamic raw);

  @protected
  SubtreeInfo dco_decode_subtree_info(dynamic raw);

  @protected
  SubtreeOperationOptions dco_decode_subtree_operation_options(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateState dco_decode_update_state(dynamic raw);

  @protected
  UpdateStatus dco_decode_update_status(dynamic raw);

  @protected
  WorkingTreeSnapshot dco_decode_working_tree_snapshot(dynamic raw);

  @protected
  WorkingTreeSnapshotPage dco_decode_working_tree_snapshot_page(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<OperationEvent> sse_decode_StreamSink_operation_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RepositoryWatchEvent>
  sse_decode_StreamSink_repository_watch_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CloneOptions sse_decode_box_autoadd_clone_options(
    SseDeserializer deserializer,
  );

  @protected
  CommitOptions sse_decode_box_autoadd_commit_options(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FileChange sse_decode_box_autoadd_file_change(SseDeserializer deserializer);

  @protected
  OperationResult sse_decode_box_autoadd_operation_result(
    SseDeserializer deserializer,
  );

  @protected
  RebasePlan sse_decode_box_autoadd_rebase_plan(SseDeserializer deserializer);

  @protected
  RepositoryInitOptions sse_decode_box_autoadd_repository_init_options(
    SseDeserializer deserializer,
  );

  @protected
  SubmoduleAddOptions sse_decode_box_autoadd_submodule_add_options(
    SseDeserializer deserializer,
  );

  @protected
  SubtreeInfo sse_decode_box_autoadd_subtree_info(SseDeserializer deserializer);

  @protected
  SubtreeOperationOptions sse_decode_box_autoadd_subtree_operation_options(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BranchInfo sse_decode_branch_info(SseDeserializer deserializer);

  @protected
  BranchPage sse_decode_branch_page(SseDeserializer deserializer);

  @protected
  ChangeKind sse_decode_change_kind(SseDeserializer deserializer);

  @protected
  CherryPickApplicability sse_decode_cherry_pick_applicability(
    SseDeserializer deserializer,
  );

  @protected
  CloneOptions sse_decode_clone_options(SseDeserializer deserializer);

  @protected
  CloneResult sse_decode_clone_result(SseDeserializer deserializer);

  @protected
  CommitCursorPage sse_decode_commit_cursor_page(SseDeserializer deserializer);

  @protected
  CommitDefaults sse_decode_commit_defaults(SseDeserializer deserializer);

  @protected
  CommitDetail sse_decode_commit_detail(SseDeserializer deserializer);

  @protected
  CommitOptions sse_decode_commit_options(SseDeserializer deserializer);

  @protected
  CommitPage sse_decode_commit_page(SseDeserializer deserializer);

  @protected
  CommitReference sse_decode_commit_reference(SseDeserializer deserializer);

  @protected
  CommitReferenceKind sse_decode_commit_reference_kind(
    SseDeserializer deserializer,
  );

  @protected
  CommitSigningMode sse_decode_commit_signing_mode(
    SseDeserializer deserializer,
  );

  @protected
  CommitSummary sse_decode_commit_summary(SseDeserializer deserializer);

  @protected
  ConflictFile sse_decode_conflict_file(SseDeserializer deserializer);

  @protected
  ConflictRegion sse_decode_conflict_region(SseDeserializer deserializer);

  @protected
  DiffDocument sse_decode_diff_document(SseDeserializer deserializer);

  @protected
  DiffFile sse_decode_diff_file(SseDeserializer deserializer);

  @protected
  DiffHunk sse_decode_diff_hunk(SseDeserializer deserializer);

  @protected
  DiffLine sse_decode_diff_line(SseDeserializer deserializer);

  @protected
  DiffLineKind sse_decode_diff_line_kind(SseDeserializer deserializer);

  @protected
  ExternalEditor sse_decode_external_editor(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileChange sse_decode_file_change(SseDeserializer deserializer);

  @protected
  FileChangePage sse_decode_file_change_page(SseDeserializer deserializer);

  @protected
  GitCapabilities sse_decode_git_capabilities(SseDeserializer deserializer);

  @protected
  GitConfigEntry sse_decode_git_config_entry(SseDeserializer deserializer);

  @protected
  GitConfigScope sse_decode_git_config_scope(SseDeserializer deserializer);

  @protected
  GitConfigSnapshot sse_decode_git_config_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  GitignoreTemplate sse_decode_gitignore_template(SseDeserializer deserializer);

  @protected
  GraphLane sse_decode_graph_lane(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BranchInfo> sse_decode_list_branch_info(SseDeserializer deserializer);

  @protected
  List<CommitReference> sse_decode_list_commit_reference(
    SseDeserializer deserializer,
  );

  @protected
  List<CommitSummary> sse_decode_list_commit_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<ConflictRegion> sse_decode_list_conflict_region(
    SseDeserializer deserializer,
  );

  @protected
  List<DiffFile> sse_decode_list_diff_file(SseDeserializer deserializer);

  @protected
  List<DiffHunk> sse_decode_list_diff_hunk(SseDeserializer deserializer);

  @protected
  List<DiffLine> sse_decode_list_diff_line(SseDeserializer deserializer);

  @protected
  List<FileChange> sse_decode_list_file_change(SseDeserializer deserializer);

  @protected
  List<GitConfigEntry> sse_decode_list_git_config_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RebasePlanItem> sse_decode_list_rebase_plan_item(
    SseDeserializer deserializer,
  );

  @protected
  List<RemoteDetails> sse_decode_list_remote_details(
    SseDeserializer deserializer,
  );

  @protected
  List<RemoteInfo> sse_decode_list_remote_info(SseDeserializer deserializer);

  @protected
  List<ResetCommit> sse_decode_list_reset_commit(SseDeserializer deserializer);

  @protected
  List<StashEntry> sse_decode_list_stash_entry(SseDeserializer deserializer);

  @protected
  List<SubmoduleInfo> sse_decode_list_submodule_info(
    SseDeserializer deserializer,
  );

  @protected
  List<SubtreeInfo> sse_decode_list_subtree_info(SseDeserializer deserializer);

  @protected
  MergeControl sse_decode_merge_control(SseDeserializer deserializer);

  @protected
  OperationEvent sse_decode_operation_event(SseDeserializer deserializer);

  @protected
  OperationPhase sse_decode_operation_phase(SseDeserializer deserializer);

  @protected
  OperationResult sse_decode_operation_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FileChange? sse_decode_opt_box_autoadd_file_change(
    SseDeserializer deserializer,
  );

  @protected
  OperationResult? sse_decode_opt_box_autoadd_operation_result(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PullMode sse_decode_pull_mode(SseDeserializer deserializer);

  @protected
  RebaseAction sse_decode_rebase_action(SseDeserializer deserializer);

  @protected
  RebaseControl sse_decode_rebase_control(SseDeserializer deserializer);

  @protected
  RebasePlan sse_decode_rebase_plan(SseDeserializer deserializer);

  @protected
  RebasePlanItem sse_decode_rebase_plan_item(SseDeserializer deserializer);

  @protected
  RemoteDetails sse_decode_remote_details(SseDeserializer deserializer);

  @protected
  RemoteInfo sse_decode_remote_info(SseDeserializer deserializer);

  @protected
  RepositoryInitOptions sse_decode_repository_init_options(
    SseDeserializer deserializer,
  );

  @protected
  RepositoryInitResult sse_decode_repository_init_result(
    SseDeserializer deserializer,
  );

  @protected
  RepositorySnapshot sse_decode_repository_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  RepositorySnapshotPage sse_decode_repository_snapshot_page(
    SseDeserializer deserializer,
  );

  @protected
  RepositoryState sse_decode_repository_state(SseDeserializer deserializer);

  @protected
  RepositoryWatchEvent sse_decode_repository_watch_event(
    SseDeserializer deserializer,
  );

  @protected
  ResetCommit sse_decode_reset_commit(SseDeserializer deserializer);

  @protected
  ResetMode sse_decode_reset_mode(SseDeserializer deserializer);

  @protected
  ResetPreview sse_decode_reset_preview(SseDeserializer deserializer);

  @protected
  SequenceControl sse_decode_sequence_control(SseDeserializer deserializer);

  @protected
  SparseCheckoutState sse_decode_sparse_checkout_state(
    SseDeserializer deserializer,
  );

  @protected
  StashEntry sse_decode_stash_entry(SseDeserializer deserializer);

  @protected
  SubmoduleAddOptions sse_decode_submodule_add_options(
    SseDeserializer deserializer,
  );

  @protected
  SubmoduleInfo sse_decode_submodule_info(SseDeserializer deserializer);

  @protected
  SubmodulePage sse_decode_submodule_page(SseDeserializer deserializer);

  @protected
  SubmoduleRemovePreview sse_decode_submodule_remove_preview(
    SseDeserializer deserializer,
  );

  @protected
  SubmoduleState sse_decode_submodule_state(SseDeserializer deserializer);

  @protected
  SubmoduleUpdateMode sse_decode_submodule_update_mode(
    SseDeserializer deserializer,
  );

  @protected
  SubtreeAction sse_decode_subtree_action(SseDeserializer deserializer);

  @protected
  SubtreeInfo sse_decode_subtree_info(SseDeserializer deserializer);

  @protected
  SubtreeOperationOptions sse_decode_subtree_operation_options(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateState sse_decode_update_state(SseDeserializer deserializer);

  @protected
  UpdateStatus sse_decode_update_status(SseDeserializer deserializer);

  @protected
  WorkingTreeSnapshot sse_decode_working_tree_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  WorkingTreeSnapshotPage sse_decode_working_tree_snapshot_page(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_operation_event_Sse(
    RustStreamSink<OperationEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_repository_watch_event_Sse(
    RustStreamSink<RepositoryWatchEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_clone_options(
    CloneOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_commit_options(
    CommitOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_file_change(
    FileChange self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_operation_result(
    OperationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rebase_plan(
    RebasePlan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_repository_init_options(
    RepositoryInitOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_submodule_add_options(
    SubmoduleAddOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_subtree_info(
    SubtreeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_subtree_operation_options(
    SubtreeOperationOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_branch_info(BranchInfo self, SseSerializer serializer);

  @protected
  void sse_encode_branch_page(BranchPage self, SseSerializer serializer);

  @protected
  void sse_encode_change_kind(ChangeKind self, SseSerializer serializer);

  @protected
  void sse_encode_cherry_pick_applicability(
    CherryPickApplicability self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clone_options(CloneOptions self, SseSerializer serializer);

  @protected
  void sse_encode_clone_result(CloneResult self, SseSerializer serializer);

  @protected
  void sse_encode_commit_cursor_page(
    CommitCursorPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_commit_defaults(
    CommitDefaults self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_commit_detail(CommitDetail self, SseSerializer serializer);

  @protected
  void sse_encode_commit_options(CommitOptions self, SseSerializer serializer);

  @protected
  void sse_encode_commit_page(CommitPage self, SseSerializer serializer);

  @protected
  void sse_encode_commit_reference(
    CommitReference self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_commit_reference_kind(
    CommitReferenceKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_commit_signing_mode(
    CommitSigningMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_commit_summary(CommitSummary self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_file(ConflictFile self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_region(
    ConflictRegion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diff_document(DiffDocument self, SseSerializer serializer);

  @protected
  void sse_encode_diff_file(DiffFile self, SseSerializer serializer);

  @protected
  void sse_encode_diff_hunk(DiffHunk self, SseSerializer serializer);

  @protected
  void sse_encode_diff_line(DiffLine self, SseSerializer serializer);

  @protected
  void sse_encode_diff_line_kind(DiffLineKind self, SseSerializer serializer);

  @protected
  void sse_encode_external_editor(
    ExternalEditor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_change(FileChange self, SseSerializer serializer);

  @protected
  void sse_encode_file_change_page(
    FileChangePage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_capabilities(
    GitCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_config_entry(
    GitConfigEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_config_scope(
    GitConfigScope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_git_config_snapshot(
    GitConfigSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gitignore_template(
    GitignoreTemplate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_graph_lane(GraphLane self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_branch_info(
    List<BranchInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_commit_reference(
    List<CommitReference> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_commit_summary(
    List<CommitSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conflict_region(
    List<ConflictRegion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_diff_file(List<DiffFile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_diff_hunk(List<DiffHunk> self, SseSerializer serializer);

  @protected
  void sse_encode_list_diff_line(List<DiffLine> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_change(
    List<FileChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_git_config_entry(
    List<GitConfigEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rebase_plan_item(
    List<RebasePlanItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_remote_details(
    List<RemoteDetails> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_remote_info(
    List<RemoteInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reset_commit(
    List<ResetCommit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stash_entry(
    List<StashEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_submodule_info(
    List<SubmoduleInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_subtree_info(
    List<SubtreeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_control(MergeControl self, SseSerializer serializer);

  @protected
  void sse_encode_operation_event(
    OperationEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_operation_phase(
    OperationPhase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_operation_result(
    OperationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_file_change(
    FileChange? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_operation_result(
    OperationResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pull_mode(PullMode self, SseSerializer serializer);

  @protected
  void sse_encode_rebase_action(RebaseAction self, SseSerializer serializer);

  @protected
  void sse_encode_rebase_control(RebaseControl self, SseSerializer serializer);

  @protected
  void sse_encode_rebase_plan(RebasePlan self, SseSerializer serializer);

  @protected
  void sse_encode_rebase_plan_item(
    RebasePlanItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remote_details(RemoteDetails self, SseSerializer serializer);

  @protected
  void sse_encode_remote_info(RemoteInfo self, SseSerializer serializer);

  @protected
  void sse_encode_repository_init_options(
    RepositoryInitOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_repository_init_result(
    RepositoryInitResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_repository_snapshot(
    RepositorySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_repository_snapshot_page(
    RepositorySnapshotPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_repository_state(
    RepositoryState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_repository_watch_event(
    RepositoryWatchEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reset_commit(ResetCommit self, SseSerializer serializer);

  @protected
  void sse_encode_reset_mode(ResetMode self, SseSerializer serializer);

  @protected
  void sse_encode_reset_preview(ResetPreview self, SseSerializer serializer);

  @protected
  void sse_encode_sequence_control(
    SequenceControl self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sparse_checkout_state(
    SparseCheckoutState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stash_entry(StashEntry self, SseSerializer serializer);

  @protected
  void sse_encode_submodule_add_options(
    SubmoduleAddOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_submodule_info(SubmoduleInfo self, SseSerializer serializer);

  @protected
  void sse_encode_submodule_page(SubmodulePage self, SseSerializer serializer);

  @protected
  void sse_encode_submodule_remove_preview(
    SubmoduleRemovePreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_submodule_state(
    SubmoduleState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_submodule_update_mode(
    SubmoduleUpdateMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtree_action(SubtreeAction self, SseSerializer serializer);

  @protected
  void sse_encode_subtree_info(SubtreeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_subtree_operation_options(
    SubtreeOperationOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_state(UpdateState self, SseSerializer serializer);

  @protected
  void sse_encode_update_status(UpdateStatus self, SseSerializer serializer);

  @protected
  void sse_encode_working_tree_snapshot(
    WorkingTreeSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_working_tree_snapshot_page(
    WorkingTreeSnapshotPage self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
