// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/git.dart';
import 'api/models.dart';
import 'api/simple.dart';
import 'api/update.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<RepositoryWatchEvent>
  dco_decode_StreamSink_repository_watch_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  RebasePlan dco_decode_box_autoadd_rebase_plan(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BranchInfo dco_decode_branch_info(dynamic raw);

  @protected
  ChangeKind dco_decode_change_kind(dynamic raw);

  @protected
  CommitDetail dco_decode_commit_detail(dynamic raw);

  @protected
  CommitPage dco_decode_commit_page(dynamic raw);

  @protected
  CommitSummary dco_decode_commit_summary(dynamic raw);

  @protected
  ConflictFile dco_decode_conflict_file(dynamic raw);

  @protected
  ConflictRegion dco_decode_conflict_region(dynamic raw);

  @protected
  DiffDocument dco_decode_diff_document(dynamic raw);

  @protected
  DiffFile dco_decode_diff_file(dynamic raw);

  @protected
  DiffHunk dco_decode_diff_hunk(dynamic raw);

  @protected
  DiffLine dco_decode_diff_line(dynamic raw);

  @protected
  DiffLineKind dco_decode_diff_line_kind(dynamic raw);

  @protected
  ExternalEditor dco_decode_external_editor(dynamic raw);

  @protected
  FileChange dco_decode_file_change(dynamic raw);

  @protected
  GraphLane dco_decode_graph_lane(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BranchInfo> dco_decode_list_branch_info(dynamic raw);

  @protected
  List<CommitSummary> dco_decode_list_commit_summary(dynamic raw);

  @protected
  List<ConflictRegion> dco_decode_list_conflict_region(dynamic raw);

  @protected
  List<DiffFile> dco_decode_list_diff_file(dynamic raw);

  @protected
  List<DiffHunk> dco_decode_list_diff_hunk(dynamic raw);

  @protected
  List<DiffLine> dco_decode_list_diff_line(dynamic raw);

  @protected
  List<FileChange> dco_decode_list_file_change(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RebasePlanItem> dco_decode_list_rebase_plan_item(dynamic raw);

  @protected
  List<RemoteInfo> dco_decode_list_remote_info(dynamic raw);

  @protected
  List<StashEntry> dco_decode_list_stash_entry(dynamic raw);

  @protected
  MergeControl dco_decode_merge_control(dynamic raw);

  @protected
  OperationResult dco_decode_operation_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PullMode dco_decode_pull_mode(dynamic raw);

  @protected
  RebaseAction dco_decode_rebase_action(dynamic raw);

  @protected
  RebaseControl dco_decode_rebase_control(dynamic raw);

  @protected
  RebasePlan dco_decode_rebase_plan(dynamic raw);

  @protected
  RebasePlanItem dco_decode_rebase_plan_item(dynamic raw);

  @protected
  RemoteInfo dco_decode_remote_info(dynamic raw);

  @protected
  RepositorySnapshot dco_decode_repository_snapshot(dynamic raw);

  @protected
  RepositoryState dco_decode_repository_state(dynamic raw);

  @protected
  RepositoryWatchEvent dco_decode_repository_watch_event(dynamic raw);

  @protected
  StashEntry dco_decode_stash_entry(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateState dco_decode_update_state(dynamic raw);

  @protected
  UpdateStatus dco_decode_update_status(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<RepositoryWatchEvent>
  sse_decode_StreamSink_repository_watch_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  RebasePlan sse_decode_box_autoadd_rebase_plan(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BranchInfo sse_decode_branch_info(SseDeserializer deserializer);

  @protected
  ChangeKind sse_decode_change_kind(SseDeserializer deserializer);

  @protected
  CommitDetail sse_decode_commit_detail(SseDeserializer deserializer);

  @protected
  CommitPage sse_decode_commit_page(SseDeserializer deserializer);

  @protected
  CommitSummary sse_decode_commit_summary(SseDeserializer deserializer);

  @protected
  ConflictFile sse_decode_conflict_file(SseDeserializer deserializer);

  @protected
  ConflictRegion sse_decode_conflict_region(SseDeserializer deserializer);

  @protected
  DiffDocument sse_decode_diff_document(SseDeserializer deserializer);

  @protected
  DiffFile sse_decode_diff_file(SseDeserializer deserializer);

  @protected
  DiffHunk sse_decode_diff_hunk(SseDeserializer deserializer);

  @protected
  DiffLine sse_decode_diff_line(SseDeserializer deserializer);

  @protected
  DiffLineKind sse_decode_diff_line_kind(SseDeserializer deserializer);

  @protected
  ExternalEditor sse_decode_external_editor(SseDeserializer deserializer);

  @protected
  FileChange sse_decode_file_change(SseDeserializer deserializer);

  @protected
  GraphLane sse_decode_graph_lane(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BranchInfo> sse_decode_list_branch_info(SseDeserializer deserializer);

  @protected
  List<CommitSummary> sse_decode_list_commit_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<ConflictRegion> sse_decode_list_conflict_region(
    SseDeserializer deserializer,
  );

  @protected
  List<DiffFile> sse_decode_list_diff_file(SseDeserializer deserializer);

  @protected
  List<DiffHunk> sse_decode_list_diff_hunk(SseDeserializer deserializer);

  @protected
  List<DiffLine> sse_decode_list_diff_line(SseDeserializer deserializer);

  @protected
  List<FileChange> sse_decode_list_file_change(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RebasePlanItem> sse_decode_list_rebase_plan_item(
    SseDeserializer deserializer,
  );

  @protected
  List<RemoteInfo> sse_decode_list_remote_info(SseDeserializer deserializer);

  @protected
  List<StashEntry> sse_decode_list_stash_entry(SseDeserializer deserializer);

  @protected
  MergeControl sse_decode_merge_control(SseDeserializer deserializer);

  @protected
  OperationResult sse_decode_operation_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PullMode sse_decode_pull_mode(SseDeserializer deserializer);

  @protected
  RebaseAction sse_decode_rebase_action(SseDeserializer deserializer);

  @protected
  RebaseControl sse_decode_rebase_control(SseDeserializer deserializer);

  @protected
  RebasePlan sse_decode_rebase_plan(SseDeserializer deserializer);

  @protected
  RebasePlanItem sse_decode_rebase_plan_item(SseDeserializer deserializer);

  @protected
  RemoteInfo sse_decode_remote_info(SseDeserializer deserializer);

  @protected
  RepositorySnapshot sse_decode_repository_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  RepositoryState sse_decode_repository_state(SseDeserializer deserializer);

  @protected
  RepositoryWatchEvent sse_decode_repository_watch_event(
    SseDeserializer deserializer,
  );

  @protected
  StashEntry sse_decode_stash_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateState sse_decode_update_state(SseDeserializer deserializer);

  @protected
  UpdateStatus sse_decode_update_status(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_repository_watch_event_Sse(
    RustStreamSink<RepositoryWatchEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rebase_plan(
    RebasePlan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_branch_info(BranchInfo self, SseSerializer serializer);

  @protected
  void sse_encode_change_kind(ChangeKind self, SseSerializer serializer);

  @protected
  void sse_encode_commit_detail(CommitDetail self, SseSerializer serializer);

  @protected
  void sse_encode_commit_page(CommitPage self, SseSerializer serializer);

  @protected
  void sse_encode_commit_summary(CommitSummary self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_file(ConflictFile self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_region(
    ConflictRegion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diff_document(DiffDocument self, SseSerializer serializer);

  @protected
  void sse_encode_diff_file(DiffFile self, SseSerializer serializer);

  @protected
  void sse_encode_diff_hunk(DiffHunk self, SseSerializer serializer);

  @protected
  void sse_encode_diff_line(DiffLine self, SseSerializer serializer);

  @protected
  void sse_encode_diff_line_kind(DiffLineKind self, SseSerializer serializer);

  @protected
  void sse_encode_external_editor(
    ExternalEditor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_change(FileChange self, SseSerializer serializer);

  @protected
  void sse_encode_graph_lane(GraphLane self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_branch_info(
    List<BranchInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_commit_summary(
    List<CommitSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conflict_region(
    List<ConflictRegion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_diff_file(List<DiffFile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_diff_hunk(List<DiffHunk> self, SseSerializer serializer);

  @protected
  void sse_encode_list_diff_line(List<DiffLine> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_change(
    List<FileChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rebase_plan_item(
    List<RebasePlanItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_remote_info(
    List<RemoteInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stash_entry(
    List<StashEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_control(MergeControl self, SseSerializer serializer);

  @protected
  void sse_encode_operation_result(
    OperationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pull_mode(PullMode self, SseSerializer serializer);

  @protected
  void sse_encode_rebase_action(RebaseAction self, SseSerializer serializer);

  @protected
  void sse_encode_rebase_control(RebaseControl self, SseSerializer serializer);

  @protected
  void sse_encode_rebase_plan(RebasePlan self, SseSerializer serializer);

  @protected
  void sse_encode_rebase_plan_item(
    RebasePlanItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remote_info(RemoteInfo self, SseSerializer serializer);

  @protected
  void sse_encode_repository_snapshot(
    RepositorySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_repository_state(
    RepositoryState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_repository_watch_event(
    RepositoryWatchEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stash_entry(StashEntry self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_state(UpdateState self, SseSerializer serializer);

  @protected
  void sse_encode_update_status(UpdateStatus self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
