// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `assign_graph_lanes`, `build_snapshot`, `cleanup_rebase_session`, `collect_branches`, `collect_remotes`, `collect_stashes`, `collect_status`, `conflict_ours_label`, `conflict_theirs_label`, `convert_diff`, `delta_status`, `display_path`, `format_git_error`, `head_information`, `is_binary`, `map_repository_state`, `next_generation`, `parse_conflict_regions`, `quoted_editor_command`, `read_blob`, `rebase_action_name`, `rebase_session_path`, `redact`, `references_by_oid`, `result_from_output`, `run_git_capture_with_stdin`, `run_git_capture`, `run_git_without_repo`, `run_git`, `safe_relative_path`, `safe_worktree_path`, `sanitize_todo`, `select_hunk`, `sequence_editor_path`, `short_reference`, `staged_kind`, `unstaged_kind`, `validate_rebase_plan`, `validate_ref_name`

Future<String> gitVersion() => RustLib.instance.api.crateApiGitGitVersion();

Future<RepositorySnapshot> openRepository({required String path}) =>
    RustLib.instance.api.crateApiGitOpenRepository(path: path);

Future<RepositorySnapshot> refreshRepository({required String path}) =>
    RustLib.instance.api.crateApiGitRefreshRepository(path: path);

Stream<RepositoryWatchEvent> watchRepository({required String path}) =>
    RustLib.instance.api.crateApiGitWatchRepository(path: path);

Future<CommitPage> listCommits({
  required String path,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiGitListCommits(
  path: path,
  offset: offset,
  limit: limit,
);

Future<CommitDetail> getCommitDetail({
  required String path,
  required String oid,
}) => RustLib.instance.api.crateApiGitGetCommitDetail(path: path, oid: oid);

Future<DiffDocument> getWorktreeDiff({
  required String path,
  String? filePath,
  required bool staged,
}) => RustLib.instance.api.crateApiGitGetWorktreeDiff(
  path: path,
  filePath: filePath,
  staged: staged,
);

Future<OperationResult> stagePaths({
  required String path,
  required List<String> paths,
}) => RustLib.instance.api.crateApiGitStagePaths(path: path, paths: paths);

Future<OperationResult> unstagePaths({
  required String path,
  required List<String> paths,
}) => RustLib.instance.api.crateApiGitUnstagePaths(path: path, paths: paths);

Future<OperationResult> applyHunk({
  required String path,
  required String filePath,
  required bool staged,
  required int hunkIndex,
  required String expectedFingerprint,
  required bool reverse,
}) => RustLib.instance.api.crateApiGitApplyHunk(
  path: path,
  filePath: filePath,
  staged: staged,
  hunkIndex: hunkIndex,
  expectedFingerprint: expectedFingerprint,
  reverse: reverse,
);

Future<OperationResult> discardFile({
  required String path,
  required String filePath,
  required bool untracked,
}) => RustLib.instance.api.crateApiGitDiscardFile(
  path: path,
  filePath: filePath,
  untracked: untracked,
);

Future<OperationResult> createCommit({
  required String path,
  required String message,
}) =>
    RustLib.instance.api.crateApiGitCreateCommit(path: path, message: message);

Future<OperationResult> cloneRepository({
  required String url,
  required String target,
}) => RustLib.instance.api.crateApiGitCloneRepository(url: url, target: target);

Future<OperationResult> createBranch({
  required String path,
  required String name,
  String? startPoint,
  required bool checkout,
}) => RustLib.instance.api.crateApiGitCreateBranch(
  path: path,
  name: name,
  startPoint: startPoint,
  checkout: checkout,
);

Future<OperationResult> switchBranch({
  required String path,
  required String name,
}) => RustLib.instance.api.crateApiGitSwitchBranch(path: path, name: name);

Future<OperationResult> renameBranch({
  required String path,
  required String oldName,
  required String newName,
}) => RustLib.instance.api.crateApiGitRenameBranch(
  path: path,
  oldName: oldName,
  newName: newName,
);

Future<OperationResult> deleteLocalBranch({
  required String path,
  required String name,
  required bool force,
}) => RustLib.instance.api.crateApiGitDeleteLocalBranch(
  path: path,
  name: name,
  force: force,
);

Future<OperationResult> fetchAll({required String path}) =>
    RustLib.instance.api.crateApiGitFetchAll(path: path);

Future<OperationResult> pull({required String path, required PullMode mode}) =>
    RustLib.instance.api.crateApiGitPull(path: path, mode: mode);

Future<OperationResult> pushCurrent({
  required String path,
  required bool forceWithLease,
  required bool setUpstream,
}) => RustLib.instance.api.crateApiGitPushCurrent(
  path: path,
  forceWithLease: forceWithLease,
  setUpstream: setUpstream,
);

Future<OperationResult> mergeBranch({
  required String path,
  required String target,
}) => RustLib.instance.api.crateApiGitMergeBranch(path: path, target: target);

Future<OperationResult> controlMerge({
  required String path,
  required MergeControl action,
}) => RustLib.instance.api.crateApiGitControlMerge(path: path, action: action);

Future<OperationResult> rebaseBranch({
  required String path,
  required String upstream,
  String? onto,
}) => RustLib.instance.api.crateApiGitRebaseBranch(
  path: path,
  upstream: upstream,
  onto: onto,
);

Future<OperationResult> controlRebase({
  required String path,
  required RebaseControl action,
}) => RustLib.instance.api.crateApiGitControlRebase(path: path, action: action);

Future<RebasePlan> prepareInteractiveRebase({
  required String path,
  required String upstream,
}) => RustLib.instance.api.crateApiGitPrepareInteractiveRebase(
  path: path,
  upstream: upstream,
);

Future<OperationResult> startInteractiveRebase({
  required String path,
  required RebasePlan plan,
}) => RustLib.instance.api.crateApiGitStartInteractiveRebase(
  path: path,
  plan: plan,
);

Future<OperationResult> stashSave({
  required String path,
  required String message,
  required bool includeUntracked,
}) => RustLib.instance.api.crateApiGitStashSave(
  path: path,
  message: message,
  includeUntracked: includeUntracked,
);

Future<OperationResult> stashApply({
  required String path,
  required int index,
  required bool pop,
}) => RustLib.instance.api.crateApiGitStashApply(
  path: path,
  index: index,
  pop: pop,
);

Future<OperationResult> stashDrop({required String path, required int index}) =>
    RustLib.instance.api.crateApiGitStashDrop(path: path, index: index);

Future<String> getStashDiff({required String path, required int index}) =>
    RustLib.instance.api.crateApiGitGetStashDiff(path: path, index: index);

Future<ConflictFile> loadConflict({
  required String path,
  required String filePath,
}) => RustLib.instance.api.crateApiGitLoadConflict(
  path: path,
  filePath: filePath,
);

Future<OperationResult> saveConflictResolution({
  required String path,
  required String filePath,
  required String content,
}) => RustLib.instance.api.crateApiGitSaveConflictResolution(
  path: path,
  filePath: filePath,
  content: content,
);

Future<OperationResult> openInVscode({
  required String path,
  required String filePath,
}) => RustLib.instance.api.crateApiGitOpenInVscode(
  path: path,
  filePath: filePath,
);

Future<OperationResult> openExternalFile({
  required String path,
  required String filePath,
  required ExternalEditor editor,
  String? customExecutable,
}) => RustLib.instance.api.crateApiGitOpenExternalFile(
  path: path,
  filePath: filePath,
  editor: editor,
  customExecutable: customExecutable,
);
