// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_operation`, `assign_graph_lanes_with_state`, `assign_graph_lanes`, `branch_page`, `build_reset_preview`, `build_snapshot`, `change_page`, `cleanup_rebase_session`, `collect_branches`, `collect_remotes`, `collect_stashes`, `collect_status`, `collect_submodules`, `config_scope`, `conflict_ours_label`, `conflict_theirs_label`, `control_sequence`, `convert_diff`, `delta_status`, `display_config_origin`, `display_path`, `ensure_clean_tracked`, `ensure_history_oids`, `ensure_no_operation_in_progress`, `find_commit`, `format_git_error`, `git_output_lines`, `gitignore_contents`, `head_information`, `hide_console_window`, `is_binary`, `is_sensitive_config_key`, `map_repository_state`, `next_generation`, `normalize_sparse_directories`, `nul_pathspec`, `parse_conflict_regions`, `quoted_editor_command`, `read_blob`, `rebase_action_name`, `rebase_session_path`, `redact`, `reference_rank`, `references_by_oid`, `replace_branch_cache`, `replace_change_cache`, `repository_cache_key`, `result_from_output`, `run_config_mutation`, `run_git_capture_with_stdin`, `run_git_capture`, `run_git_without_repo_named`, `run_git_without_repo_raw`, `run_git`, `safe_relative_path`, `safe_worktree_path`, `sanitize_todo`, `select_hunk_lines`, `select_hunk`, `sequence_editor_path`, `short_reference`, `staged_kind`, `start_history_cache`, `submodule_fingerprint`, `submodule_page`, `submodule_remove_fingerprint`, `submodule_update_command`, `unstaged_kind`, `untracked_collision_root`, `validate_branch_name`, `validate_config_component`, `validate_config_key`, `validate_config_value`, `validate_identity`, `validate_mainline`, `validate_optional_url`, `validate_rebase_plan`, `validate_ref_name`, `validate_remote_name`, `validate_subtree_values`, `validate_tag_name`, `write_subtree_registry_unlocked`, `write_subtree_registry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BranchCache`, `ChangeCache`, `HistoryCache`, `SubmoduleCache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `fmt`, `fmt`, `fmt`, `fmt`

Future<String> gitVersion() => RustLib.instance.api.crateApiGitGitVersion();

Future<GitCapabilities> gitCapabilities() =>
    RustLib.instance.api.crateApiGitGitCapabilities();

Future<RepositorySnapshot> openRepository({required String path}) =>
    RustLib.instance.api.crateApiGitOpenRepository(path: path);

Future<RepositorySnapshot> refreshRepository({required String path}) =>
    RustLib.instance.api.crateApiGitRefreshRepository(path: path);

Future<WorkingTreeSnapshot> refreshWorkingTree({required String path}) =>
    RustLib.instance.api.crateApiGitRefreshWorkingTree(path: path);

Future<RepositorySnapshotPage> openRepositoryPaged({
  required String path,
  required int changeLimit,
}) => RustLib.instance.api.crateApiGitOpenRepositoryPaged(
  path: path,
  changeLimit: changeLimit,
);

Future<RepositorySnapshotPage> refreshRepositoryPaged({
  required String path,
  required int changeLimit,
}) => RustLib.instance.api.crateApiGitRefreshRepositoryPaged(
  path: path,
  changeLimit: changeLimit,
);

Future<WorkingTreeSnapshotPage> refreshWorkingTreePaged({
  required String path,
  required int changeLimit,
}) => RustLib.instance.api.crateApiGitRefreshWorkingTreePaged(
  path: path,
  changeLimit: changeLimit,
);

Future<FileChangePage> listChangesCursor({
  required String path,
  required String cursor,
  required int limit,
}) => RustLib.instance.api.crateApiGitListChangesCursor(
  path: path,
  cursor: cursor,
  limit: limit,
);

Future<BranchPage> listBranchesCursor({
  required String path,
  required String cursor,
  required int limit,
}) => RustLib.instance.api.crateApiGitListBranchesCursor(
  path: path,
  cursor: cursor,
  limit: limit,
);

Future<FileChange?> getCachedFileChange({
  required String path,
  required String filePath,
}) => RustLib.instance.api.crateApiGitGetCachedFileChange(
  path: path,
  filePath: filePath,
);

Stream<RepositoryWatchEvent> watchRepository({required String path}) =>
    RustLib.instance.api.crateApiGitWatchRepository(path: path);

Future<CommitPage> listCommits({
  required String path,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiGitListCommits(
  path: path,
  offset: offset,
  limit: limit,
);

/// Returns a stable cursor page without replaying or fully consuming the
/// revwalk for every page.
///
/// A background reader owns the revwalk and advances it only far enough to
/// produce the visible page plus one look-ahead commit. Commit metadata and
/// graph lanes are materialized lazily as pages become visible. A cursor is
/// tied to the current HEAD and is rejected after history changes.
Future<CommitCursorPage> listCommitsCursor({
  required String path,
  String? cursor,
  required int limit,
}) => RustLib.instance.api.crateApiGitListCommitsCursor(
  path: path,
  cursor: cursor,
  limit: limit,
);

Future<CommitDetail> getCommitDetail({
  required String path,
  required String oid,
}) => RustLib.instance.api.crateApiGitGetCommitDetail(path: path, oid: oid);

Future<DiffDocument> compareCommits({
  required String path,
  required String fromOid,
  required String toOid,
}) => RustLib.instance.api.crateApiGitCompareCommits(
  path: path,
  fromOid: fromOid,
  toOid: toOid,
);

Future<DiffDocument> getWorktreeDiff({
  required String path,
  String? filePath,
  required bool staged,
}) => RustLib.instance.api.crateApiGitGetWorktreeDiff(
  path: path,
  filePath: filePath,
  staged: staged,
);

Future<OperationResult> stagePaths({
  required String path,
  required List<String> paths,
}) => RustLib.instance.api.crateApiGitStagePaths(path: path, paths: paths);

Future<OperationResult> unstagePaths({
  required String path,
  required List<String> paths,
}) => RustLib.instance.api.crateApiGitUnstagePaths(path: path, paths: paths);

Future<OperationResult> intentToAdd({
  required String path,
  required List<String> paths,
}) => RustLib.instance.api.crateApiGitIntentToAdd(path: path, paths: paths);

Future<OperationResult> applyHunk({
  required String path,
  required String filePath,
  required bool staged,
  required int hunkIndex,
  required String expectedFingerprint,
  required bool reverse,
}) => RustLib.instance.api.crateApiGitApplyHunk(
  path: path,
  filePath: filePath,
  staged: staged,
  hunkIndex: hunkIndex,
  expectedFingerprint: expectedFingerprint,
  reverse: reverse,
);

Future<OperationResult> applyHunkLines({
  required String path,
  required String filePath,
  required bool staged,
  required int hunkIndex,
  required List<int> lineIndices,
  required String expectedFingerprint,
  required bool reverse,
}) => RustLib.instance.api.crateApiGitApplyHunkLines(
  path: path,
  filePath: filePath,
  staged: staged,
  hunkIndex: hunkIndex,
  lineIndices: lineIndices,
  expectedFingerprint: expectedFingerprint,
  reverse: reverse,
);

Future<OperationResult> discardFile({
  required String path,
  required String filePath,
  required bool untracked,
}) => RustLib.instance.api.crateApiGitDiscardFile(
  path: path,
  filePath: filePath,
  untracked: untracked,
);

Future<OperationResult> createCommit({
  required String path,
  required String message,
}) =>
    RustLib.instance.api.crateApiGitCreateCommit(path: path, message: message);

Future<CommitDefaults> loadCommitDefaults({required String path}) =>
    RustLib.instance.api.crateApiGitLoadCommitDefaults(path: path);

Future<OperationResult> createCommitWithOptions({
  required String path,
  required CommitOptions options,
}) => RustLib.instance.api.crateApiGitCreateCommitWithOptions(
  path: path,
  options: options,
);

Future<OperationResult> createTag({
  required String path,
  required String targetOid,
  required String name,
  required bool annotated,
  String? message,
}) => RustLib.instance.api.crateApiGitCreateTag(
  path: path,
  targetOid: targetOid,
  name: name,
  annotated: annotated,
  message: message,
);

Future<OperationResult> checkoutCommit({
  required String path,
  required String oid,
}) => RustLib.instance.api.crateApiGitCheckoutCommit(path: path, oid: oid);

Future<OperationResult> cherryPickCommit({
  required String path,
  required String oid,
  int? mainlineParent,
}) => RustLib.instance.api.crateApiGitCherryPickCommit(
  path: path,
  oid: oid,
  mainlineParent: mainlineParent,
);

/// Simulates a single-commit cherry-pick against HEAD without changing the
/// repository. Unlike an ancestry or patch-id check, this correctly allows an
/// old commit whose effect was removed by a later revert.
Future<CherryPickApplicability> assessCherryPick({
  required String path,
  required String oid,
  int? mainlineParent,
}) => RustLib.instance.api.crateApiGitAssessCherryPick(
  path: path,
  oid: oid,
  mainlineParent: mainlineParent,
);

Future<OperationResult> controlCherryPick({
  required String path,
  required SequenceControl action,
}) => RustLib.instance.api.crateApiGitControlCherryPick(
  path: path,
  action: action,
);

Future<OperationResult> revertCommit({
  required String path,
  required String oid,
  int? mainlineParent,
}) => RustLib.instance.api.crateApiGitRevertCommit(
  path: path,
  oid: oid,
  mainlineParent: mainlineParent,
);

Future<OperationResult> controlRevert({
  required String path,
  required SequenceControl action,
}) => RustLib.instance.api.crateApiGitControlRevert(path: path, action: action);

Future<ResetPreview> previewReset({
  required String path,
  required String targetOid,
}) => RustLib.instance.api.crateApiGitPreviewReset(
  path: path,
  targetOid: targetOid,
);

Future<OperationResult> resetToCommit({
  required String path,
  required String targetOid,
  required ResetMode mode,
  required String expectedFingerprint,
  String? branchConfirmation,
}) => RustLib.instance.api.crateApiGitResetToCommit(
  path: path,
  targetOid: targetOid,
  mode: mode,
  expectedFingerprint: expectedFingerprint,
  branchConfirmation: branchConfirmation,
);

Future<RepositoryInitResult> initializeRepository({
  required RepositoryInitOptions options,
}) => RustLib.instance.api.crateApiGitInitializeRepository(options: options);

Future<OperationResult> cloneRepository({
  required String url,
  required String target,
}) => RustLib.instance.api.crateApiGitCloneRepository(url: url, target: target);

Future<CloneResult> cloneRepositoryAdvanced({required CloneOptions options}) =>
    RustLib.instance.api.crateApiGitCloneRepositoryAdvanced(options: options);

Future<GitConfigSnapshot> readGitConfig({String? path}) =>
    RustLib.instance.api.crateApiGitReadGitConfig(path: path);

Future<OperationResult> setGitConfig({
  String? path,
  required GitConfigScope scope,
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiGitSetGitConfig(
  path: path,
  scope: scope,
  key: key,
  value: value,
);

Future<OperationResult> addGitConfigValue({
  String? path,
  required GitConfigScope scope,
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiGitAddGitConfigValue(
  path: path,
  scope: scope,
  key: key,
  value: value,
);

Future<OperationResult> unsetGitConfigValue({
  String? path,
  required GitConfigScope scope,
  required String key,
  String? value,
}) => RustLib.instance.api.crateApiGitUnsetGitConfigValue(
  path: path,
  scope: scope,
  key: key,
  value: value,
);

Future<List<RemoteDetails>> listRemoteDetails({required String path}) =>
    RustLib.instance.api.crateApiGitListRemoteDetails(path: path);

Future<OperationResult> addRemote({
  required String path,
  required String name,
  required String fetchUrl,
}) => RustLib.instance.api.crateApiGitAddRemote(
  path: path,
  name: name,
  fetchUrl: fetchUrl,
);

Future<OperationResult> renameRemote({
  required String path,
  required String oldName,
  required String newName,
}) => RustLib.instance.api.crateApiGitRenameRemote(
  path: path,
  oldName: oldName,
  newName: newName,
);

Future<OperationResult> updateRemote({
  required String path,
  required String name,
  required String fetchUrl,
  String? pushUrl,
}) => RustLib.instance.api.crateApiGitUpdateRemote(
  path: path,
  name: name,
  fetchUrl: fetchUrl,
  pushUrl: pushUrl,
);

Future<OperationResult> removeRemote({
  required String path,
  required String name,
}) => RustLib.instance.api.crateApiGitRemoveRemote(path: path, name: name);

Future<OperationResult> createTrackingBranch({
  required String path,
  required String remoteBranch,
  required String localBranch,
}) => RustLib.instance.api.crateApiGitCreateTrackingBranch(
  path: path,
  remoteBranch: remoteBranch,
  localBranch: localBranch,
);

Future<SparseCheckoutState> readSparseCheckout({required String path}) =>
    RustLib.instance.api.crateApiGitReadSparseCheckout(path: path);

Future<OperationResult> setSparseCheckout({
  required String path,
  required List<String> directories,
}) => RustLib.instance.api.crateApiGitSetSparseCheckout(
  path: path,
  directories: directories,
);

Future<OperationResult> disableSparseCheckout({required String path}) =>
    RustLib.instance.api.crateApiGitDisableSparseCheckout(path: path);

Future<SubmodulePage> listSubmodules({
  required String path,
  required bool recursive,
  required int limit,
}) => RustLib.instance.api.crateApiGitListSubmodules(
  path: path,
  recursive: recursive,
  limit: limit,
);

Future<SubmodulePage> listSubmodulesCursor({
  required String path,
  required String cursor,
  required int limit,
}) => RustLib.instance.api.crateApiGitListSubmodulesCursor(
  path: path,
  cursor: cursor,
  limit: limit,
);

Future<OperationResult> initSubmodules({
  required String path,
  required List<String> paths,
  required bool recursive,
}) => RustLib.instance.api.crateApiGitInitSubmodules(
  path: path,
  paths: paths,
  recursive: recursive,
);

Future<OperationResult> updateSubmodules({
  required String path,
  required List<String> paths,
  required bool recursive,
  required SubmoduleUpdateMode mode,
}) => RustLib.instance.api.crateApiGitUpdateSubmodules(
  path: path,
  paths: paths,
  recursive: recursive,
  mode: mode,
);

Future<OperationResult> syncSubmodules({
  required String path,
  required List<String> paths,
  required bool recursive,
}) => RustLib.instance.api.crateApiGitSyncSubmodules(
  path: path,
  paths: paths,
  recursive: recursive,
);

Future<OperationResult> addSubmodule({
  required String path,
  required SubmoduleAddOptions options,
}) =>
    RustLib.instance.api.crateApiGitAddSubmodule(path: path, options: options);

Future<SubmoduleRemovePreview> previewRemoveSubmodule({
  required String path,
  required String submodulePath,
}) => RustLib.instance.api.crateApiGitPreviewRemoveSubmodule(
  path: path,
  submodulePath: submodulePath,
);

Future<OperationResult> removeSubmodule({
  required String path,
  required String submodulePath,
  required String expectedFingerprint,
  required String confirmation,
}) => RustLib.instance.api.crateApiGitRemoveSubmodule(
  path: path,
  submodulePath: submodulePath,
  expectedFingerprint: expectedFingerprint,
  confirmation: confirmation,
);

Future<List<SubtreeInfo>> listSubtrees({required String path}) =>
    RustLib.instance.api.crateApiGitListSubtrees(path: path);

Future<OperationResult> registerSubtree({
  required String path,
  required SubtreeInfo subtree,
}) => RustLib.instance.api.crateApiGitRegisterSubtree(
  path: path,
  subtree: subtree,
);

Future<OperationResult> forgetSubtree({
  required String path,
  required String id,
}) => RustLib.instance.api.crateApiGitForgetSubtree(path: path, id: id);

Future<OperationResult> createBranch({
  required String path,
  required String name,
  String? startPoint,
  required bool checkout,
}) => RustLib.instance.api.crateApiGitCreateBranch(
  path: path,
  name: name,
  startPoint: startPoint,
  checkout: checkout,
);

Future<OperationResult> switchBranch({
  required String path,
  required String name,
}) => RustLib.instance.api.crateApiGitSwitchBranch(path: path, name: name);

Future<OperationResult> renameBranch({
  required String path,
  required String oldName,
  required String newName,
}) => RustLib.instance.api.crateApiGitRenameBranch(
  path: path,
  oldName: oldName,
  newName: newName,
);

Future<OperationResult> deleteLocalBranch({
  required String path,
  required String name,
  required bool force,
}) => RustLib.instance.api.crateApiGitDeleteLocalBranch(
  path: path,
  name: name,
  force: force,
);

Future<OperationResult> fetchAll({required String path}) =>
    RustLib.instance.api.crateApiGitFetchAll(path: path);

Future<OperationResult> pull({required String path, required PullMode mode}) =>
    RustLib.instance.api.crateApiGitPull(path: path, mode: mode);

Future<OperationResult> pushCurrent({
  required String path,
  required bool forceWithLease,
  required bool setUpstream,
}) => RustLib.instance.api.crateApiGitPushCurrent(
  path: path,
  forceWithLease: forceWithLease,
  setUpstream: setUpstream,
);

Future<OperationResult> pushCurrentTo({
  required String path,
  required String remote,
  required String remoteBranch,
  required bool forceWithLease,
}) => RustLib.instance.api.crateApiGitPushCurrentTo(
  path: path,
  remote: remote,
  remoteBranch: remoteBranch,
  forceWithLease: forceWithLease,
);

Future<OperationResult> mergeBranch({
  required String path,
  required String target,
}) => RustLib.instance.api.crateApiGitMergeBranch(path: path, target: target);

Future<OperationResult> controlMerge({
  required String path,
  required MergeControl action,
}) => RustLib.instance.api.crateApiGitControlMerge(path: path, action: action);

Future<OperationResult> rebaseBranch({
  required String path,
  required String upstream,
  String? onto,
}) => RustLib.instance.api.crateApiGitRebaseBranch(
  path: path,
  upstream: upstream,
  onto: onto,
);

Future<OperationResult> controlRebase({
  required String path,
  required RebaseControl action,
}) => RustLib.instance.api.crateApiGitControlRebase(path: path, action: action);

Future<RebasePlan> prepareInteractiveRebase({
  required String path,
  required String upstream,
}) => RustLib.instance.api.crateApiGitPrepareInteractiveRebase(
  path: path,
  upstream: upstream,
);

Future<OperationResult> startInteractiveRebase({
  required String path,
  required RebasePlan plan,
}) => RustLib.instance.api.crateApiGitStartInteractiveRebase(
  path: path,
  plan: plan,
);

Future<OperationResult> stashSave({
  required String path,
  required String message,
  required bool includeUntracked,
}) => RustLib.instance.api.crateApiGitStashSave(
  path: path,
  message: message,
  includeUntracked: includeUntracked,
);

Future<OperationResult> stashApply({
  required String path,
  required int index,
  required bool pop,
}) => RustLib.instance.api.crateApiGitStashApply(
  path: path,
  index: index,
  pop: pop,
);

Future<OperationResult> stashDrop({required String path, required int index}) =>
    RustLib.instance.api.crateApiGitStashDrop(path: path, index: index);

Future<String> getStashDiff({required String path, required int index}) =>
    RustLib.instance.api.crateApiGitGetStashDiff(path: path, index: index);

Future<ConflictFile> loadConflict({
  required String path,
  required String filePath,
}) => RustLib.instance.api.crateApiGitLoadConflict(
  path: path,
  filePath: filePath,
);

Future<OperationResult> saveConflictResolution({
  required String path,
  required String filePath,
  required String content,
}) => RustLib.instance.api.crateApiGitSaveConflictResolution(
  path: path,
  filePath: filePath,
  content: content,
);

Future<OperationResult> openInVscode({
  required String path,
  required String filePath,
}) => RustLib.instance.api.crateApiGitOpenInVscode(
  path: path,
  filePath: filePath,
);

Future<OperationResult> openExternalFile({
  required String path,
  required String filePath,
  required ExternalEditor editor,
  String? customExecutable,
}) => RustLib.instance.api.crateApiGitOpenExternalFile(
  path: path,
  filePath: filePath,
  editor: editor,
  customExecutable: customExecutable,
);

Stream<OperationEvent> runSubtreeOperation({
  required String path,
  required String operationId,
  required SubtreeOperationOptions options,
}) => RustLib.instance.api.crateApiGitRunSubtreeOperation(
  path: path,
  operationId: operationId,
  options: options,
);

Future<OperationResult> cancelGitOperation({required String operationId}) =>
    RustLib.instance.api.crateApiGitCancelGitOperation(
      operationId: operationId,
    );
