// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GitError`, `OperationEvent`, `OperationPhase`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BranchInfo {
  final String name;
  final String fullName;
  final String? oid;
  final bool isHead;
  final bool isRemote;
  final String? upstream;
  final PlatformInt64 ahead;
  final PlatformInt64 behind;

  const BranchInfo({
    required this.name,
    required this.fullName,
    this.oid,
    required this.isHead,
    required this.isRemote,
    this.upstream,
    required this.ahead,
    required this.behind,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      fullName.hashCode ^
      oid.hashCode ^
      isHead.hashCode ^
      isRemote.hashCode ^
      upstream.hashCode ^
      ahead.hashCode ^
      behind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BranchInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fullName == other.fullName &&
          oid == other.oid &&
          isHead == other.isHead &&
          isRemote == other.isRemote &&
          upstream == other.upstream &&
          ahead == other.ahead &&
          behind == other.behind;
}

class BranchPage {
  final List<BranchInfo> branches;
  final String? nextCursor;
  final int totalBranches;

  const BranchPage({
    required this.branches,
    this.nextCursor,
    required this.totalBranches,
  });

  @override
  int get hashCode =>
      branches.hashCode ^ nextCursor.hashCode ^ totalBranches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BranchPage &&
          runtimeType == other.runtimeType &&
          branches == other.branches &&
          nextCursor == other.nextCursor &&
          totalBranches == other.totalBranches;
}

enum ChangeKind {
  none,
  added,
  modified,
  deleted,
  renamed,
  typeChanged,
  untracked,
  conflicted,
  unreadable,
}

enum CherryPickApplicability { applicable, alreadyApplied, conflicts }

class CloneOptions {
  final String url;
  final String target;
  final String remoteName;
  final String? branch;
  final int? depth;
  final bool singleBranch;
  final bool noTags;
  final bool recurseSubmodules;
  final bool shallowSubmodules;
  final bool blobless;
  final List<String> sparseDirectories;

  const CloneOptions({
    required this.url,
    required this.target,
    required this.remoteName,
    this.branch,
    this.depth,
    required this.singleBranch,
    required this.noTags,
    required this.recurseSubmodules,
    required this.shallowSubmodules,
    required this.blobless,
    required this.sparseDirectories,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      target.hashCode ^
      remoteName.hashCode ^
      branch.hashCode ^
      depth.hashCode ^
      singleBranch.hashCode ^
      noTags.hashCode ^
      recurseSubmodules.hashCode ^
      shallowSubmodules.hashCode ^
      blobless.hashCode ^
      sparseDirectories.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloneOptions &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          target == other.target &&
          remoteName == other.remoteName &&
          branch == other.branch &&
          depth == other.depth &&
          singleBranch == other.singleBranch &&
          noTags == other.noTags &&
          recurseSubmodules == other.recurseSubmodules &&
          shallowSubmodules == other.shallowSubmodules &&
          blobless == other.blobless &&
          sparseDirectories == other.sparseDirectories;
}

class CloneResult {
  final String path;
  final OperationResult operation;
  final List<String> warnings;

  const CloneResult({
    required this.path,
    required this.operation,
    required this.warnings,
  });

  @override
  int get hashCode => path.hashCode ^ operation.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloneResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          operation == other.operation &&
          warnings == other.warnings;
}

class CommitCursorPage {
  final List<CommitSummary> commits;
  final String? nextCursor;
  final int totalCommits;

  const CommitCursorPage({
    required this.commits,
    this.nextCursor,
    required this.totalCommits,
  });

  @override
  int get hashCode =>
      commits.hashCode ^ nextCursor.hashCode ^ totalCommits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitCursorPage &&
          runtimeType == other.runtimeType &&
          commits == other.commits &&
          nextCursor == other.nextCursor &&
          totalCommits == other.totalCommits;
}

class CommitDefaults {
  final String template;
  final String? cleanup;
  final bool signingEnabled;
  final String? previousMessage;

  const CommitDefaults({
    required this.template,
    this.cleanup,
    required this.signingEnabled,
    this.previousMessage,
  });

  @override
  int get hashCode =>
      template.hashCode ^
      cleanup.hashCode ^
      signingEnabled.hashCode ^
      previousMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitDefaults &&
          runtimeType == other.runtimeType &&
          template == other.template &&
          cleanup == other.cleanup &&
          signingEnabled == other.signingEnabled &&
          previousMessage == other.previousMessage;
}

class CommitDetail {
  final String oid;
  final String message;
  final String authorName;
  final String authorEmail;
  final PlatformInt64 authoredAt;
  final String committerName;
  final String committerEmail;
  final PlatformInt64 committedAt;
  final List<String> parentOids;
  final DiffDocument diff;

  const CommitDetail({
    required this.oid,
    required this.message,
    required this.authorName,
    required this.authorEmail,
    required this.authoredAt,
    required this.committerName,
    required this.committerEmail,
    required this.committedAt,
    required this.parentOids,
    required this.diff,
  });

  @override
  int get hashCode =>
      oid.hashCode ^
      message.hashCode ^
      authorName.hashCode ^
      authorEmail.hashCode ^
      authoredAt.hashCode ^
      committerName.hashCode ^
      committerEmail.hashCode ^
      committedAt.hashCode ^
      parentOids.hashCode ^
      diff.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitDetail &&
          runtimeType == other.runtimeType &&
          oid == other.oid &&
          message == other.message &&
          authorName == other.authorName &&
          authorEmail == other.authorEmail &&
          authoredAt == other.authoredAt &&
          committerName == other.committerName &&
          committerEmail == other.committerEmail &&
          committedAt == other.committedAt &&
          parentOids == other.parentOids &&
          diff == other.diff;
}

class CommitOptions {
  final String? message;
  final bool amend;
  final bool signoff;
  final CommitSigningMode signing;
  final String? authorName;
  final String? authorEmail;
  final String? authoredAt;
  final bool allowEmpty;
  final String? fixupTarget;
  final String? squashTarget;

  const CommitOptions({
    this.message,
    required this.amend,
    required this.signoff,
    required this.signing,
    this.authorName,
    this.authorEmail,
    this.authoredAt,
    required this.allowEmpty,
    this.fixupTarget,
    this.squashTarget,
  });

  @override
  int get hashCode =>
      message.hashCode ^
      amend.hashCode ^
      signoff.hashCode ^
      signing.hashCode ^
      authorName.hashCode ^
      authorEmail.hashCode ^
      authoredAt.hashCode ^
      allowEmpty.hashCode ^
      fixupTarget.hashCode ^
      squashTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitOptions &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          amend == other.amend &&
          signoff == other.signoff &&
          signing == other.signing &&
          authorName == other.authorName &&
          authorEmail == other.authorEmail &&
          authoredAt == other.authoredAt &&
          allowEmpty == other.allowEmpty &&
          fixupTarget == other.fixupTarget &&
          squashTarget == other.squashTarget;
}

class CommitPage {
  final List<CommitSummary> commits;
  final int? nextOffset;

  const CommitPage({required this.commits, this.nextOffset});

  @override
  int get hashCode => commits.hashCode ^ nextOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitPage &&
          runtimeType == other.runtimeType &&
          commits == other.commits &&
          nextOffset == other.nextOffset;
}

class CommitReference {
  final String name;
  final String fullName;
  final CommitReferenceKind kind;

  const CommitReference({
    required this.name,
    required this.fullName,
    required this.kind,
  });

  @override
  int get hashCode => name.hashCode ^ fullName.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitReference &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fullName == other.fullName &&
          kind == other.kind;
}

enum CommitReferenceKind { head, localBranch, remoteBranch, tag }

enum CommitSigningMode { useConfig, sign, doNotSign }

class CommitSummary {
  final String oid;
  final String shortOid;
  final String summary;
  final String authorName;
  final String authorEmail;
  final PlatformInt64 authoredAt;
  final List<String> parentOids;
  final List<CommitReference> references;
  final GraphLane lane;

  const CommitSummary({
    required this.oid,
    required this.shortOid,
    required this.summary,
    required this.authorName,
    required this.authorEmail,
    required this.authoredAt,
    required this.parentOids,
    required this.references,
    required this.lane,
  });

  @override
  int get hashCode =>
      oid.hashCode ^
      shortOid.hashCode ^
      summary.hashCode ^
      authorName.hashCode ^
      authorEmail.hashCode ^
      authoredAt.hashCode ^
      parentOids.hashCode ^
      references.hashCode ^
      lane.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitSummary &&
          runtimeType == other.runtimeType &&
          oid == other.oid &&
          shortOid == other.shortOid &&
          summary == other.summary &&
          authorName == other.authorName &&
          authorEmail == other.authorEmail &&
          authoredAt == other.authoredAt &&
          parentOids == other.parentOids &&
          references == other.references &&
          lane == other.lane;
}

class ConflictFile {
  final String path;
  final String baseLabel;
  final String oursLabel;
  final String theirsLabel;
  final String base;
  final String ours;
  final String theirs;
  final String current;
  final List<ConflictRegion> regions;
  final bool binary;
  final bool tooLarge;

  const ConflictFile({
    required this.path,
    required this.baseLabel,
    required this.oursLabel,
    required this.theirsLabel,
    required this.base,
    required this.ours,
    required this.theirs,
    required this.current,
    required this.regions,
    required this.binary,
    required this.tooLarge,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      baseLabel.hashCode ^
      oursLabel.hashCode ^
      theirsLabel.hashCode ^
      base.hashCode ^
      ours.hashCode ^
      theirs.hashCode ^
      current.hashCode ^
      regions.hashCode ^
      binary.hashCode ^
      tooLarge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          baseLabel == other.baseLabel &&
          oursLabel == other.oursLabel &&
          theirsLabel == other.theirsLabel &&
          base == other.base &&
          ours == other.ours &&
          theirs == other.theirs &&
          current == other.current &&
          regions == other.regions &&
          binary == other.binary &&
          tooLarge == other.tooLarge;
}

class ConflictRegion {
  final int index;
  final String base;
  final String ours;
  final String theirs;

  const ConflictRegion({
    required this.index,
    required this.base,
    required this.ours,
    required this.theirs,
  });

  @override
  int get hashCode =>
      index.hashCode ^ base.hashCode ^ ours.hashCode ^ theirs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictRegion &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          base == other.base &&
          ours == other.ours &&
          theirs == other.theirs;
}

class DiffDocument {
  final String fingerprint;
  final bool staged;
  final List<DiffFile> files;

  const DiffDocument({
    required this.fingerprint,
    required this.staged,
    required this.files,
  });

  @override
  int get hashCode => fingerprint.hashCode ^ staged.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffDocument &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          staged == other.staged &&
          files == other.files;
}

class DiffFile {
  final String? oldPath;
  final String? newPath;
  final String status;
  final bool binary;
  final bool tooLarge;
  final List<DiffHunk> hunks;

  const DiffFile({
    this.oldPath,
    this.newPath,
    required this.status,
    required this.binary,
    required this.tooLarge,
    required this.hunks,
  });

  @override
  int get hashCode =>
      oldPath.hashCode ^
      newPath.hashCode ^
      status.hashCode ^
      binary.hashCode ^
      tooLarge.hashCode ^
      hunks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffFile &&
          runtimeType == other.runtimeType &&
          oldPath == other.oldPath &&
          newPath == other.newPath &&
          status == other.status &&
          binary == other.binary &&
          tooLarge == other.tooLarge &&
          hunks == other.hunks;
}

class DiffHunk {
  final int index;
  final String header;
  final int oldStart;
  final int oldLines;
  final int newStart;
  final int newLines;
  final List<DiffLine> lines;

  const DiffHunk({
    required this.index,
    required this.header,
    required this.oldStart,
    required this.oldLines,
    required this.newStart,
    required this.newLines,
    required this.lines,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      header.hashCode ^
      oldStart.hashCode ^
      oldLines.hashCode ^
      newStart.hashCode ^
      newLines.hashCode ^
      lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffHunk &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          header == other.header &&
          oldStart == other.oldStart &&
          oldLines == other.oldLines &&
          newStart == other.newStart &&
          newLines == other.newLines &&
          lines == other.lines;
}

class DiffLine {
  final DiffLineKind kind;
  final int? oldLine;
  final int? newLine;
  final String content;

  const DiffLine({
    required this.kind,
    this.oldLine,
    this.newLine,
    required this.content,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ oldLine.hashCode ^ newLine.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiffLine &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          oldLine == other.oldLine &&
          newLine == other.newLine &&
          content == other.content;
}

enum DiffLineKind { context, addition, deletion, header }

enum ExternalEditor { vsCode, systemDefault, gitMergeTool, custom }

class FileChange {
  final String path;
  final String? oldPath;
  final ChangeKind staged;
  final ChangeKind unstaged;
  final bool conflicted;
  final bool untracked;

  const FileChange({
    required this.path,
    this.oldPath,
    required this.staged,
    required this.unstaged,
    required this.conflicted,
    required this.untracked,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      oldPath.hashCode ^
      staged.hashCode ^
      unstaged.hashCode ^
      conflicted.hashCode ^
      untracked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileChange &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          oldPath == other.oldPath &&
          staged == other.staged &&
          unstaged == other.unstaged &&
          conflicted == other.conflicted &&
          untracked == other.untracked;
}

class FileChangePage {
  final List<FileChange> files;
  final String? nextCursor;
  final int totalFiles;
  final int stagedCount;
  final int unstagedCount;
  final int conflictCount;
  final int untrackedCount;

  const FileChangePage({
    required this.files,
    this.nextCursor,
    required this.totalFiles,
    required this.stagedCount,
    required this.unstagedCount,
    required this.conflictCount,
    required this.untrackedCount,
  });

  @override
  int get hashCode =>
      files.hashCode ^
      nextCursor.hashCode ^
      totalFiles.hashCode ^
      stagedCount.hashCode ^
      unstagedCount.hashCode ^
      conflictCount.hashCode ^
      untrackedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileChangePage &&
          runtimeType == other.runtimeType &&
          files == other.files &&
          nextCursor == other.nextCursor &&
          totalFiles == other.totalFiles &&
          stagedCount == other.stagedCount &&
          unstagedCount == other.unstagedCount &&
          conflictCount == other.conflictCount &&
          untrackedCount == other.untrackedCount;
}

class GitCapabilities {
  final String version;
  final bool supportsRepositorySetup;
  final bool supportsFixedValueConfig;
  final bool supportsSparseCheckout;

  const GitCapabilities({
    required this.version,
    required this.supportsRepositorySetup,
    required this.supportsFixedValueConfig,
    required this.supportsSparseCheckout,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      supportsRepositorySetup.hashCode ^
      supportsFixedValueConfig.hashCode ^
      supportsSparseCheckout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCapabilities &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          supportsRepositorySetup == other.supportsRepositorySetup &&
          supportsFixedValueConfig == other.supportsFixedValueConfig &&
          supportsSparseCheckout == other.supportsSparseCheckout;
}

class GitConfigEntry {
  final String key;
  final String value;
  final GitConfigScope scope;
  final String origin;
  final bool inherited;
  final bool sensitive;

  const GitConfigEntry({
    required this.key,
    required this.value,
    required this.scope,
    required this.origin,
    required this.inherited,
    required this.sensitive,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      value.hashCode ^
      scope.hashCode ^
      origin.hashCode ^
      inherited.hashCode ^
      sensitive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitConfigEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value &&
          scope == other.scope &&
          origin == other.origin &&
          inherited == other.inherited &&
          sensitive == other.sensitive;
}

enum GitConfigScope { system, global, local, worktree, command, unknown }

class GitConfigSnapshot {
  final List<GitConfigEntry> entries;

  const GitConfigSnapshot({required this.entries});

  @override
  int get hashCode => entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitConfigSnapshot &&
          runtimeType == other.runtimeType &&
          entries == other.entries;
}

enum GitignoreTemplate { none, flutter, rust, node, python, visualStudio }

class GraphLane {
  final int column;
  final Uint32List parentColumns;

  const GraphLane({required this.column, required this.parentColumns});

  @override
  int get hashCode => column.hashCode ^ parentColumns.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphLane &&
          runtimeType == other.runtimeType &&
          column == other.column &&
          parentColumns == other.parentColumns;
}

enum MergeControl { continue_, abort }

class OperationResult {
  final bool success;
  final int exitCode;
  final String summary;
  final String stdout;
  final String stderr;

  const OperationResult({
    required this.success,
    required this.exitCode,
    required this.summary,
    required this.stdout,
    required this.stderr,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      exitCode.hashCode ^
      summary.hashCode ^
      stdout.hashCode ^
      stderr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OperationResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          exitCode == other.exitCode &&
          summary == other.summary &&
          stdout == other.stdout &&
          stderr == other.stderr;
}

enum PullMode { configured, merge, rebase, fastForwardOnly }

enum RebaseAction { pick, reword, squash, fixup, drop }

enum RebaseControl { continue_, skip, abort }

class RebasePlan {
  final String upstream;
  final String? onto;
  final List<RebasePlanItem> items;
  final bool containsMergeCommits;

  const RebasePlan({
    required this.upstream,
    this.onto,
    required this.items,
    required this.containsMergeCommits,
  });

  @override
  int get hashCode =>
      upstream.hashCode ^
      onto.hashCode ^
      items.hashCode ^
      containsMergeCommits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RebasePlan &&
          runtimeType == other.runtimeType &&
          upstream == other.upstream &&
          onto == other.onto &&
          items == other.items &&
          containsMergeCommits == other.containsMergeCommits;
}

class RebasePlanItem {
  final RebaseAction action;
  final String oid;
  final String summary;
  final String? newMessage;

  const RebasePlanItem({
    required this.action,
    required this.oid,
    required this.summary,
    this.newMessage,
  });

  @override
  int get hashCode =>
      action.hashCode ^ oid.hashCode ^ summary.hashCode ^ newMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RebasePlanItem &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          oid == other.oid &&
          summary == other.summary &&
          newMessage == other.newMessage;
}

class RemoteDetails {
  final String name;
  final List<String> fetchUrls;
  final List<String> pushUrls;

  const RemoteDetails({
    required this.name,
    required this.fetchUrls,
    required this.pushUrls,
  });

  @override
  int get hashCode => name.hashCode ^ fetchUrls.hashCode ^ pushUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteDetails &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fetchUrls == other.fetchUrls &&
          pushUrls == other.pushUrls;
}

class RemoteInfo {
  final String name;
  final String? fetchUrl;
  final String? pushUrl;

  const RemoteInfo({required this.name, this.fetchUrl, this.pushUrl});

  @override
  int get hashCode => name.hashCode ^ fetchUrl.hashCode ^ pushUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fetchUrl == other.fetchUrl &&
          pushUrl == other.pushUrl;
}

class RepositoryInitOptions {
  final String targetPath;
  final String initialBranch;
  final bool createReadme;
  final GitignoreTemplate gitignoreTemplate;
  final String? originUrl;

  const RepositoryInitOptions({
    required this.targetPath,
    required this.initialBranch,
    required this.createReadme,
    required this.gitignoreTemplate,
    this.originUrl,
  });

  @override
  int get hashCode =>
      targetPath.hashCode ^
      initialBranch.hashCode ^
      createReadme.hashCode ^
      gitignoreTemplate.hashCode ^
      originUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepositoryInitOptions &&
          runtimeType == other.runtimeType &&
          targetPath == other.targetPath &&
          initialBranch == other.initialBranch &&
          createReadme == other.createReadme &&
          gitignoreTemplate == other.gitignoreTemplate &&
          originUrl == other.originUrl;
}

class RepositoryInitResult {
  final String path;
  final OperationResult operation;
  final List<String> warnings;

  const RepositoryInitResult({
    required this.path,
    required this.operation,
    required this.warnings,
  });

  @override
  int get hashCode => path.hashCode ^ operation.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepositoryInitResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          operation == other.operation &&
          warnings == other.warnings;
}

class RepositorySnapshot {
  final String repositoryPath;
  final String workdir;
  final String name;
  final String? headName;
  final String? headOid;
  final String? upstream;
  final PlatformInt64 ahead;
  final PlatformInt64 behind;
  final RepositoryState state;
  final BigInt generation;
  final List<FileChange> files;
  final List<BranchInfo> branches;
  final List<RemoteInfo> remotes;
  final List<StashEntry> stashes;

  const RepositorySnapshot({
    required this.repositoryPath,
    required this.workdir,
    required this.name,
    this.headName,
    this.headOid,
    this.upstream,
    required this.ahead,
    required this.behind,
    required this.state,
    required this.generation,
    required this.files,
    required this.branches,
    required this.remotes,
    required this.stashes,
  });

  @override
  int get hashCode =>
      repositoryPath.hashCode ^
      workdir.hashCode ^
      name.hashCode ^
      headName.hashCode ^
      headOid.hashCode ^
      upstream.hashCode ^
      ahead.hashCode ^
      behind.hashCode ^
      state.hashCode ^
      generation.hashCode ^
      files.hashCode ^
      branches.hashCode ^
      remotes.hashCode ^
      stashes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepositorySnapshot &&
          runtimeType == other.runtimeType &&
          repositoryPath == other.repositoryPath &&
          workdir == other.workdir &&
          name == other.name &&
          headName == other.headName &&
          headOid == other.headOid &&
          upstream == other.upstream &&
          ahead == other.ahead &&
          behind == other.behind &&
          state == other.state &&
          generation == other.generation &&
          files == other.files &&
          branches == other.branches &&
          remotes == other.remotes &&
          stashes == other.stashes;
}

class RepositorySnapshotPage {
  final RepositorySnapshot snapshot;
  final FileChangePage changes;
  final BranchPage branches;

  const RepositorySnapshotPage({
    required this.snapshot,
    required this.changes,
    required this.branches,
  });

  @override
  int get hashCode => snapshot.hashCode ^ changes.hashCode ^ branches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepositorySnapshotPage &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          changes == other.changes &&
          branches == other.branches;
}

enum RepositoryState {
  clean,
  merge,
  rebase,
  rebaseInteractive,
  rebaseMerge,
  cherryPick,
  revert,
  bisect,
  applyMailbox,
  unknown,
}

class RepositoryWatchEvent {
  final String repositoryPath;
  final List<String> paths;

  const RepositoryWatchEvent({
    required this.repositoryPath,
    required this.paths,
  });

  @override
  int get hashCode => repositoryPath.hashCode ^ paths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepositoryWatchEvent &&
          runtimeType == other.runtimeType &&
          repositoryPath == other.repositoryPath &&
          paths == other.paths;
}

class ResetCommit {
  final String oid;
  final String shortOid;
  final String summary;

  const ResetCommit({
    required this.oid,
    required this.shortOid,
    required this.summary,
  });

  @override
  int get hashCode => oid.hashCode ^ shortOid.hashCode ^ summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResetCommit &&
          runtimeType == other.runtimeType &&
          oid == other.oid &&
          shortOid == other.shortOid &&
          summary == other.summary;
}

enum ResetMode { soft, mixed, hard }

class ResetPreview {
  final String currentBranch;
  final String targetOid;
  final List<ResetCommit> outgoingCommits;
  final List<String> trackedPaths;
  final List<String> untrackedCollisions;
  final String fingerprint;

  const ResetPreview({
    required this.currentBranch,
    required this.targetOid,
    required this.outgoingCommits,
    required this.trackedPaths,
    required this.untrackedCollisions,
    required this.fingerprint,
  });

  @override
  int get hashCode =>
      currentBranch.hashCode ^
      targetOid.hashCode ^
      outgoingCommits.hashCode ^
      trackedPaths.hashCode ^
      untrackedCollisions.hashCode ^
      fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResetPreview &&
          runtimeType == other.runtimeType &&
          currentBranch == other.currentBranch &&
          targetOid == other.targetOid &&
          outgoingCommits == other.outgoingCommits &&
          trackedPaths == other.trackedPaths &&
          untrackedCollisions == other.untrackedCollisions &&
          fingerprint == other.fingerprint;
}

enum SequenceControl { continue_, skip, abort }

class SparseCheckoutState {
  final bool enabled;
  final bool coneMode;
  final List<String> directories;

  const SparseCheckoutState({
    required this.enabled,
    required this.coneMode,
    required this.directories,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ coneMode.hashCode ^ directories.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SparseCheckoutState &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          coneMode == other.coneMode &&
          directories == other.directories;
}

class StashEntry {
  final int index;
  final String message;
  final String oid;

  const StashEntry({
    required this.index,
    required this.message,
    required this.oid,
  });

  @override
  int get hashCode => index.hashCode ^ message.hashCode ^ oid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StashEntry &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          message == other.message &&
          oid == other.oid;
}

enum UpdateState { disabled, notInstalled, upToDate, available, downloaded }

class UpdateStatus {
  final UpdateState state;
  final String currentVersion;
  final String? availableVersion;
  final String? releaseNotesMarkdown;
  final BigInt? downloadSize;
  final String message;

  const UpdateStatus({
    required this.state,
    required this.currentVersion,
    this.availableVersion,
    this.releaseNotesMarkdown,
    this.downloadSize,
    required this.message,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      currentVersion.hashCode ^
      availableVersion.hashCode ^
      releaseNotesMarkdown.hashCode ^
      downloadSize.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          currentVersion == other.currentVersion &&
          availableVersion == other.availableVersion &&
          releaseNotesMarkdown == other.releaseNotesMarkdown &&
          downloadSize == other.downloadSize &&
          message == other.message;
}

class WorkingTreeSnapshot {
  final BigInt generation;
  final RepositoryState state;
  final List<FileChange> files;

  const WorkingTreeSnapshot({
    required this.generation,
    required this.state,
    required this.files,
  });

  @override
  int get hashCode => generation.hashCode ^ state.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkingTreeSnapshot &&
          runtimeType == other.runtimeType &&
          generation == other.generation &&
          state == other.state &&
          files == other.files;
}

class WorkingTreeSnapshotPage {
  final WorkingTreeSnapshot snapshot;
  final FileChangePage changes;

  const WorkingTreeSnapshotPage({
    required this.snapshot,
    required this.changes,
  });

  @override
  int get hashCode => snapshot.hashCode ^ changes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkingTreeSnapshotPage &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          changes == other.changes;
}
