// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `disabled_status`, `manager`, `status_from_update`, `update_repository`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `gitfront_velopack_bootstrap`

Future<UpdateStatus> checkForUpdate() =>
    RustLib.instance.api.crateApiUpdateCheckForUpdate();

Future<UpdateStatus> downloadUpdate() =>
    RustLib.instance.api.crateApiUpdateDownloadUpdate();

Future<void> applyUpdateAndRestart() =>
    RustLib.instance.api.crateApiUpdateApplyUpdateAndRestart();
